# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a8fecc1d17dfc3e1fd200a7c45e81b881e6937f6df6e53c0f2f760526ad5fd5181331d31dd72c9a2dca742a1bcd957184bbfd817897c14aed186c433413cf7

test:
  secret_key_base: a1de40c33d3204e211f260d196c3e279a4d45ba4cfe2e51a2c3a529c8a11170fe4fa7b58ff422de5b053dbff867e188978dacccf66a67322483c337e5ac405a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
